[pytest]
pythonpath = .
testpaths = tests
asyncio_mode = auto
filterwarnings =
    ignore::DeprecationWarning:pydub.utils
    ignore::DeprecationWarning:websockets.legacy
    ignore::DeprecationWarning:uvicorn.protocols.websockets
